# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-eforce-imx-a5x"
BBFILE_PATTERN_meta-eforce-imx-a5x = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-eforce-imx-a5x = "6"

LAYERDEPENDS_meta-eforce-imx-a5x = "core"
LAYERSERIES_COMPAT_meta-eforce-imx-a5x = "scarthgap"


